### ISSUE TITLE
Read from stdin

### ISSUE THREAD

**Issue by sitiom** [marcoradocchia/qr-rs#1]
This doesn't currently work:
![image](https://user-images.githubusercontent.com/56180050/179342329-2f973be3-2008-4596-8684-c628b38b3eee.png)

It would be nice to be able to read input from stdin and pipe commands to qr-rs.

**Comment by marcoradocchia** [comment]
Sure it would be nice! I'll work on this feature and it will be merged for the next release.

P.S.: meanwhile, if you need to encode the output of some other program, you could use _command substitution_, like `qr "$(fortune)"`.
